// Build both shipping artefacts from the ES modules in js/:
//
//   js/bundle.js       the hosted app, one file, loaded as ./js/bundle.js?v=BUILD
//   dist/seminary.html the whole app in a single file, no server needed
//
//   node tools/build.mjs
//
// The bundle exists to make cache-busting possible. When index.html loaded a
// module graph, a stale service worker could serve a fresh index.html beside
// five stale modules, and a version query on the page URL only busted the page.
// One file means one cache key: ?v=N invalidates the entire app at once.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => readFileSync(resolve(ROOT, p), 'utf8');

// Dependency order: each module may only import ones already defined above it.
const MODULES = ['text', 'store', 'schedule', 'notify', 'library'];

/** Rewrite one ES module into `const __mod_x = (() => { ... })()`. */
function moduleToIife(name, source) {
  const bindings = [];

  let body = source
    .replace(/^import\s+\*\s+as\s+(\w+)\s+from\s+'\.\/(\w+)\.js';$/gm, (_, ns, mod) => {
      bindings.push(`const ${ns} = __mod_${mod};`);
      return '';
    })
    .replace(/^import\s+\{([^}]+)\}\s+from\s+'\.\/(\w+)\.js';$/gm, (_, names, mod) => {
      // "EM as EM_MARK" is an import alias, and destructuring spells the same
      // thing "EM: EM_MARK". Passed through unchanged it is a syntax error, and
      // one that only shows up in the built bundle — the modules themselves run
      // fine — so it is worth the three lines to translate here.
      const bound = names
        .split(',')
        .map((part) => part.trim())
        .filter(Boolean)
        .map((part) => part.replace(/^(\S+)\s+as\s+(\S+)$/, '$1: $2'))
        .join(', ');
      bindings.push(`const {${bound}} = __mod_${mod};`);
      return '';
    });

  const exported = [];
  body = body.replace(/^export\s+(async\s+)?(function|const|let|var|class)\s+(\w+)/gm, (m, _a, _k, id) => {
    exported.push(id);
    return m.replace(/^export\s+/, '');
  });

  if (/^export\s/m.test(body)) throw new Error(`${name}: unsupported export form`);

  return [
    `const __mod_${name} = (() => {`,
    ...bindings,
    body.trim(),
    `return { ${exported.join(', ')} };`,
    '})();'
  ].join('\n');
}

const appSource = read('js/app.js');

// The build stamp shown in the app and used as the ?v= cache key. Read from the
// source so there is exactly one place to bump it.
const buildMatch = appSource.match(/^const BUILD = '([^']+)';$/m);
if (!buildMatch) throw new Error('js/app.js must declare: const BUILD = \'...\';');
const BUILD = buildMatch[1];
const VERSION = BUILD.split(' ')[0]; // "v6"

const parts = MODULES.map((m) => moduleToIife(m, read(`js/${m}.js`)));
const app = moduleToIife('app', appSource).replace(/^const __mod_app = /, '');
const bundle = [`// Generated by tools/build.mjs — edit js/*.js, not this file.`, ...parts, app].join('\n');

writeFileSync(resolve(ROOT, 'js/bundle.js'), `${bundle}\n`);

/* ---------- the hosted page points at the versioned bundle ---------- */

const indexPath = resolve(ROOT, 'index.html');
let index = readFileSync(indexPath, 'utf8');
const before = index;
index = index.replace(
  /<script type="module" src="\.\/js\/(?:app|bundle)\.js(?:\?v=[^"]*)?"><\/script>/,
  `<script type="module" src="./js/bundle.js?v=${VERSION}"></script>`
);
if (index === before && !index.includes(`bundle.js?v=${VERSION}`)) {
  throw new Error('index.html has no recognisable app script tag to version');
}
writeFileSync(indexPath, index);

/* ---------- the offline single-file copy ---------- */

const courses = JSON.parse(read('data/courses.json'));
const iconSvg = read('icons/icon.svg');
const iconDataUri = `data:image/svg+xml;base64,${Buffer.from(iconSvg).toString('base64')}`;

const single = index
  .replace(/<link rel="manifest"[^>]*>\s*/, '')
  .replace(/<link rel="icon"[^>]*>/, `<link rel="icon" href="${iconDataUri}" type="image/svg+xml" />`)
  .replace(/<link rel="apple-touch-icon"[^>]*>/, `<link rel="apple-touch-icon" href="${iconDataUri}" />`)
  .replace(/<link rel="stylesheet"[^>]*>/, `<style>\n${read('css/styles.css')}\n</style>`)
  .replace(
    /<script type="module" src="\.\/js\/bundle\.js\?v=[^"]*"><\/script>/,
    ['<script type="module">', `globalThis.__COURSES__ = ${JSON.stringify(courses)};`, bundle, '</script>'].join('\n')
  )
  .replace('<title>Seminary — Today</title>', '<title>Seminary — Today (offline)</title>');

mkdirSync(resolve(ROOT, 'dist'), { recursive: true });
writeFileSync(resolve(ROOT, 'dist/seminary.html'), single);

console.log(`build ${BUILD}`);
console.log(`  js/bundle.js        ${(bundle.length / 1024).toFixed(0)} KB  (index.html -> ?v=${VERSION})`);
console.log(`  dist/seminary.html  ${(single.length / 1024).toFixed(0)} KB`);
